### ISSUE TITLE
No matching distribution found in Debian 9

### ISSUE THREAD

**Issue by ruslanguns** [rostgaard/Twisted-PJSUA#6]
Hi,

Firs of all, thanks for your contribution...

I am getting the following error at executing the command: sudo apt-get install python-pip libasound2-dev && sudo pip install twisted-web2

```
  Could not find a version that satisfies the requirement twisted-web2 (from versions: )
No matching distribution found for twisted-web2
```

Thanks in advance!
Ruslan

**Comment by rostgaard** [comment]
Hi Ruslan
Please note that this is quite old and largely unmaintained repository, so I cannot guarantee that the code still works.
That being said, you can try to install twisted via apt instead of via pip: apt-get install python-twisted
